In [51]:
# xarray to read NETCDF
import numpy as np
import pandas as pd
import dask.dataframe as dd
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
# Opening CHIRPS data
chirps = xr.open_dataset('data/CHIRPS/chirps-v2.0.monthly.nc')

In [53]:
# Subset chirps to South Sudan and convert to Dataframe
south_sudan = chirps.sel(latitude=slice(3.5, 12.5), longitude=slice(25, 35))
south_sudan_df = south_sudan.to_dataframe()
# Calculate region average
south_sudan_region_average = south_sudan_df.groupby(['time']).mean().reset_index()
south_sudan_region_average['month'] = south_sudan_region_average['time'].dt.month
south_sudan_monthly_average = south_sudan_region_average.drop('time', axis=1).groupby('month').mean()
south_sudan_monthly_average

           precip
month
1        3.765411
2        7.002088
3       29.369036
4       59.940136
5      106.829948
6      132.397385
7      165.392960
8      176.251312
9      140.835266
10     107.240044
11      28.783758
12       6.974833

In [54]:
# Subset chirps to Eastern East Africa and convert to Dataframe
eastern_east_africa = chirps.sel(latitude=slice(-3.5, 8), longitude=slice(38, 50))
eastern_east_africa_df = eastern_east_africa.to_dataframe()
# Calculate region average
eastern_east_africa_region_average = eastern_east_africa_df.groupby(['time']).mean().reset_index()
eastern_east_africa_region_average['month'] = eastern_east_africa_region_average['time'].dt.month
eastern_east_africa_monthly_average = eastern_east_africa_region_average.drop('time', axis=1).groupby('month').mean()
eastern_east_africa_monthly_average

           precip
month
1        6.146791
2        6.856639
3       30.842974
4      109.086815
5       72.667366
6       17.044243
7       18.403734
8       15.704654
9       19.691940
10      74.863808
11      64.423309
12      23.576805

In [55]:
# Subset chirps to Eastern Ukraine and convert to Dataframe
eastern_ukraine = chirps.sel(latitude=slice(45, 51), longitude=slice(31, 40))
eastern_ukraine_df = eastern_ukraine.to_dataframe()
# Calculate region average
eastern_ukraine_region_average = eastern_ukraine_df.groupby(['time']).mean().reset_index()
eastern_ukraine_region_average['month'] = eastern_ukraine_region_average['time'].dt.month
eastern_ukraine_monthly_average = eastern_ukraine_region_average.drop('time', axis=1).groupby('month').mean()
eastern_ukraine_monthly_average

          precip
month
1      44.531723
2      35.422230
3      36.691719
4      38.593143
5      48.876381
6      66.469635
7      54.695667
8      40.164089
9      42.482620
10     38.510197
11     44.273655
12     47.498512

In [56]:
# Subset chirps to Southern Africa and convert to Dataframe
southern_africa = chirps.sel(latitude=slice(-23, -15), longitude=slice(25, 34))
southern_africa_df = southern_africa.to_dataframe()
# Calculate region average
southern_africa_region_average = southern_africa_df.groupby(['time']).mean().reset_index()
southern_africa_region_average['month'] = southern_africa_region_average['time'].dt.month
southern_africa_monthly_average = southern_africa_region_average.drop('time', axis=1).groupby('month').mean()
southern_africa_monthly_average

           precip
month
1      163.638123
2      128.692215
3       73.080170
4       23.747215
5        5.480103
6        4.029397
7        3.110784
8        2.695528
9        4.825752
10      21.229612
11      66.845657
12     137.114166

In [57]:
# Subset chirps to West Africa and convert to Dataframe
west_africa = chirps.sel(latitude=slice(10, 13.5), longitude=slice(-10, 0))
west_africa_df = west_africa.to_dataframe()
# Calculate region average
west_africa_df_region_average = west_africa_df.groupby(['time']).mean().reset_index()
west_africa_df_region_average['month'] = west_africa_df_region_average['time'].dt.month
west_africa_df_region_average = west_africa_df_region_average.drop('time', axis=1).groupby('month').mean()
west_africa_df_region_average

           precip
month
1        0.578514
2        1.809930
3        9.186115
4       31.423784
5       75.844315
6      125.414337
7      205.544006
8      261.857941
9      173.663757
10      60.701622
11       4.490495
12       1.429900

In [58]:
# Subset chirps to Sri Lanka and convert to Dataframe
sri_lanka = chirps.sel(latitude=slice(5.5, 10), longitude=slice(79.5, 82))
sri_lanka_df = sri_lanka.to_dataframe()
# Calculate region average
sri_lanka_region_average = sri_lanka_df.groupby(['time']).mean().reset_index()
sri_lanka_region_average['month'] = sri_lanka_region_average['time'].dt.month
sri_lanka_region_average = sri_lanka_region_average.drop('time', axis=1).groupby('month').mean()
sri_lanka_region_average

           precip
month
1      130.200989
2       80.712822
3       87.358574
4      147.998230
5      156.453415
6       77.554489
7       67.973152
8       75.645058
9      131.904678
10     251.232117
11     329.087311
12     235.360825

In [59]:
# Subset chirps to Lake Victoria Basin and convert to Dataframe
lake_victoria_basin = chirps.sel(latitude=slice(-4, 1.5), longitude=slice(29, 36))
lake_victoria_basin_df = lake_victoria_basin.to_dataframe()
# Calculate region average
lake_victoria_basin_region_average = lake_victoria_basin_df.groupby(['time']).mean().reset_index()
lake_victoria_basin_region_average['month'] = lake_victoria_basin_region_average['time'].dt.month
lake_victoria_basin_region_average = lake_victoria_basin_region_average.drop('time', axis=1).groupby('month').mean()
lake_victoria_basin_region_average

           precip
month
1       80.800598
2       75.941269
3      137.537323
4      183.445770
5      120.294434
6       49.018204
7       41.184097
8       64.712433
9       76.353943
10     112.537476
11     134.848526
12     112.568962