# Selection of Dry Masked Months

This notebook details how we selected the months to dry mask in our heatmap plots.

Outline:
- Open CHIRPS
- Subset to a region of interest
- For every month, view the average observed precipitation
- View the months where precipitation is less than or equal to 10mm per month

In [ ]:
# xarray to read NETCDF
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Opening CHIRPS data
chirps = xr.open_dataset('data/CHIRPS/chirps-v2.0.monthly.nc')

In [ ]:
# Subset chirps to South Sudan and convert to Dataframe
south_sudan = chirps.sel(latitude=slice(3.5, 12.5), longitude=slice(25, 35))
south_sudan_df = south_sudan.to_dataframe()
# Calculate region average
south_sudan_region_average = south_sudan_df.groupby(['time']).mean().reset_index()
south_sudan_region_average['month'] = south_sudan_region_average['time'].dt.month
south_sudan_monthly_average = south_sudan_region_average.drop('time', axis=1).groupby('month').mean()
south_sudan_monthly_average[south_sudan_monthly_average['precip'] <= 10]

         precip
month
1      3.765411
2      7.002088
12     6.974833

In [ ]:
# Subset chirps to Eastern East Africa and convert to Dataframe
eastern_east_africa = chirps.sel(latitude=slice(-3.5, 8), longitude=slice(38, 50))
eastern_east_africa_df = eastern_east_africa.to_dataframe()
# Calculate region average
eastern_east_africa_region_average = eastern_east_africa_df.groupby(['time']).mean().reset_index()
eastern_east_africa_region_average['month'] = eastern_east_africa_region_average['time'].dt.month
eastern_east_africa_monthly_average = eastern_east_africa_region_average.drop('time', axis=1).groupby('month').mean()
eastern_east_africa_monthly_average[eastern_east_africa_monthly_average['precip'] <= 10]

         precip
month
1      6.146791
2      6.856639

In [ ]:
# Subset chirps to Eastern Ukraine and convert to Dataframe
eastern_ukraine = chirps.sel(latitude=slice(45, 51), longitude=slice(31, 40))
eastern_ukraine_df = eastern_ukraine.to_dataframe()
# Calculate region average
eastern_ukraine_region_average = eastern_ukraine_df.groupby(['time']).mean().reset_index()
eastern_ukraine_region_average['month'] = eastern_ukraine_region_average['time'].dt.month
eastern_ukraine_monthly_average = eastern_ukraine_region_average.drop('time', axis=1).groupby('month').mean()
eastern_ukraine_monthly_average[eastern_ukraine_monthly_average['precip'] <= 10]

Empty DataFrame
Columns: [precip]
Index: []

In [ ]:
# Subset chirps to Southern Africa and convert to Dataframe
southern_africa = chirps.sel(latitude=slice(-23, -15), longitude=slice(25, 34))
southern_africa_df = southern_africa.to_dataframe()
# Calculate region average
southern_africa_region_average = southern_africa_df.groupby(['time']).mean().reset_index()
southern_africa_region_average['month'] = southern_africa_region_average['time'].dt.month
southern_africa_monthly_average = southern_africa_region_average.drop('time', axis=1).groupby('month').mean()
southern_africa_monthly_average[southern_africa_monthly_average['precip'] <= 10]

         precip
month
5      5.480103
6      4.029397
7      3.110784
8      2.695528
9      4.825752

In [ ]:
# Subset chirps to West Africa and convert to Dataframe
west_africa = chirps.sel(latitude=slice(10, 13.5), longitude=slice(-10, 0))
west_africa_df = west_africa.to_dataframe()
# Calculate region average
west_africa_df_region_average = west_africa_df.groupby(['time']).mean().reset_index()
west_africa_df_region_average['month'] = west_africa_df_region_average['time'].dt.month
west_africa_df_region_average = west_africa_df_region_average.drop('time', axis=1).groupby('month').mean()
west_africa_df_region_average[west_africa_df_region_average['precip'] <= 10]

         precip
month
1      0.578514
2      1.809930
3      9.186115
11     4.490495
12     1.429900

In [ ]:
# Subset chirps to Sri Lanka and convert to Dataframe
sri_lanka = chirps.sel(latitude=slice(5.5, 10), longitude=slice(79.5, 82))
sri_lanka_df = sri_lanka.to_dataframe()
# Calculate region average
sri_lanka_region_average = sri_lanka_df.groupby(['time']).mean().reset_index()
sri_lanka_region_average['month'] = sri_lanka_region_average['time'].dt.month
sri_lanka_region_average = sri_lanka_region_average.drop('time', axis=1).groupby('month').mean()
sri_lanka_region_average[sri_lanka_region_average['precip'] <= 10]

Empty DataFrame
Columns: [precip]
Index: []

In [ ]:
# Subset chirps to Lake Victoria Basin and convert to Dataframe
lake_victoria_basin = chirps.sel(latitude=slice(-4, 1.5), longitude=slice(29, 36))
lake_victoria_basin_df = lake_victoria_basin.to_dataframe()
# Calculate region average
lake_victoria_basin_region_average = lake_victoria_basin_df.groupby(['time']).mean().reset_index()
lake_victoria_basin_region_average['month'] = lake_victoria_basin_region_average['time'].dt.month
lake_victoria_basin_region_average = lake_victoria_basin_region_average.drop('time', axis=1).groupby('month').mean()
lake_victoria_basin_region_average[lake_victoria_basin_region_average['precip'] <= 10]

Empty DataFrame
Columns: [precip]
Index: []

# Now, we will define the following dry masking dictionary in our heatmap plotting code

In [ ]:
dry_mask_months = {
    'south_sudan': [1, 2, 12],
    'eastern_east_africa': [1, 2],
    'southern_africa': [5, 6, 7, 8, 9],
    'west_africa': [1, 2, 3, 11, 12]
}